name: Deploy Static Website to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
<<<<<<< HEAD
          aws-region: eu-north-1  # change region if needed
=======
          aws-region: eu-north-1   # change region if needed
>>>>>>> b4507bdd2ff2154b76e85d8de24b42afb52c641a

      - name: Sync files to S3
        run: |
          aws s3 sync ./ s3://my-password-checker-site001/ --delete
